In [27]:
try:
  a = 10
  b = 0
  print(a//b)
except:
  print("Error..!")

Error..!


In [28]:
n = str(121)
print('Equal' if n == (str(n)[::-1]) else "not Equal")

Equal


In [29]:
try:
  import numpy as np
  import pandas as pd
  import matplotlib.pyplot as plt
  print('Library Loaded .........')
except:
  print('One or More Library was not Found ! ')

Library Loaded .........


READ DATA SET

In [30]:
df = pd.read_csv("DataSets/iris.csv")

In [31]:
df.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [33]:
df.describe()

sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

DATA PREPROCESSING

In [34]:
pd.unique(df.species)

array(['setosa', 'versicolor', 'virginica'], dtype=object)

# **Checking for missing values using isnull()**

In [35]:
df.isnull()

sepal_length  sepal_width  petal_length  petal_width  species
0           False        False         False        False    False
1           False        False         False        False    False
2           False        False         False        False    False
3           False        False         False        False    False
4           False        False         False        False    False
..            ...          ...           ...          ...      ...
145         False        False         False        False    False
146         False        False         False        False    False
147         False        False         False        False    False
148         False        False         False        False    False
149         False        False         False        False    False

[150 rows x 5 columns]

# *Fill NA values with a global constant ("0")*

In [36]:
# df.fillna("0", inplace=True)

# *Fill NA values with a Mode of That attribute*

In [ ]:
# # Fill missing values with the mode
#df_filled = df.apply(lambda x: x.fillna(x.mode().iloc[0]))

# **DATA TRANSFORMATION Str to Int**

In [37]:
def change_string_to_int(column):
    variables=pd.unique(df[column])
    for item in range(variables.size):
        df[column]=[item if each==variables[item] else each for each in df[column]]
    return df[column]

In [38]:
df["species"]=change_string_to_int("species")

## *Min Max - Normalization*

In [39]:
#  n_V = (V - min(A))|(max(A) - min(A))  {(new_max(A)-new_min(A))+new_min(A)}
df_new = (df - df.min())/(df.max()-df.min())

In [40]:
pd.unique(df.species)

array([0, 1, 2], dtype=int64)

In [41]:
df_new.head()

sepal_length  sepal_width  petal_length  petal_width  species
0      0.222222     0.625000      0.067797     0.041667      0.0
1      0.166667     0.416667      0.067797     0.041667      0.0
2      0.111111     0.500000      0.050847     0.041667      0.0
3      0.083333     0.458333      0.084746     0.041667      0.0
4      0.194444     0.666667      0.067797     0.041667      0.0

In [42]:
pd.unique(df_new.species)

array([0. , 0.5, 1. ])

# *Z-Score Normalization*

x' = (x - μ) / σ

In [43]:
# x' = (x - μ) / σ
df_zscore = (df - df.mean())/df.var()

In [44]:
df_zscore.head()

sepal_length  sepal_width  petal_length  petal_width  species
0     -1.084061     2.372290     -0.757639    -1.714701    -1.49
1     -1.375736    -0.287228     -0.757639    -1.714701    -1.49
2     -1.667412     0.776579     -0.789761    -1.714701    -1.49
3     -1.813249     0.244676     -0.725518    -1.714701    -1.49
4     -1.229898     2.904193     -0.757639    -1.714701    -1.49

In [45]:
pd.unique(df_zscore.species)

array([-1.49,  0.  ,  1.49])

# *Normalization by Decimal Scaling*

In [50]:
df_decimal_scaling = {}
no_of_coloums = df.columns
for i in no_of_coloums:
  size_decimal = str(df[i].astype(int).max())
  df_decimal_scaling[i] = df[i]/(10**(len(size_decimal)))

In [54]:
pd.DataFrame(df_decimal_scaling)

sepal_length  sepal_width  petal_length  petal_width  species
0            0.51         0.35          0.14         0.02      0.0
1            0.49         0.30          0.14         0.02      0.0
2            0.47         0.32          0.13         0.02      0.0
3            0.46         0.31          0.15         0.02      0.0
4            0.50         0.36          0.14         0.02      0.0
..            ...          ...           ...          ...      ...
145          0.67         0.30          0.52         0.23      0.2
146          0.63         0.25          0.50         0.19      0.2
147          0.65         0.30          0.52         0.20      0.2
148          0.62         0.34          0.54         0.23      0.2
149          0.59         0.30          0.51         0.18      0.2

[150 rows x 5 columns]

In [65]:
pd.unique(df_decimal_scaling["species"])

array([0. , 0.1, 0.2])